BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBXXXXXXXXXXXXX XXXXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXX XXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                            XXXXXX
                            XXX XXXXXXXXXXXXXXXX XXXXX X XXXXXXXXX XXX XXXX XXXXX XX XXX XXXXXXXXX
                            XXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXX XXXXXX XXXXXXXXXXXXX XX XXXX XXXX XXX XXXXXX
                                    XXX XXXXX XXXXXXXXXX
                            XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXX XX XXXXXXXXXXXXXXX
                            XXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXX
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB