BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXXXX XX X XXXXXXX XXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX
XXXXXXX XX X XXXXXXX XXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX
XXXXXXX XXXX XX XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXX
XXXXXXXXX XXXXX
XXXXXXX XX X XXXXXXX XXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX
XXXXXXX XX X XXXXXXX XXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX
XXXXXXX XXXX XX XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
    XXXX XXXXX XXXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX


    XXXX XXXXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

    XXXX XXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
XXXXXXX

XXXXX BBBBB BBBBBBBBBBBBX
BBB BBBBBBBBBBBB BB BBBBBBBB
BB BBBBBBBBBBBB BB BBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

    BBBBB BBBBBBB
    BBBBBBBB

    BBBBBBB BBBBBBBBBBBBBBBBBBBBB

    XXXX XXXX XXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX
    XXXXXX

    XXXX XXXX XXXXX XXXX XXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXX XXXXX XXXXX XXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

     #
 #
 #
 #
 #
 #
 #
 #
 #
 #


    XXXX XXXXXX XX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XXXXXXXX XX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX