# Generated by Django 5.1.5 on 2025-01-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogauthormodel_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blogs.blogmodel'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(to='blogs.blogcategorymodel', verbose_name='categories'),
        ),
    ]
