# Generated by Django 5.1.5 on 2025-01-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogcommentmodel_blog_alter_blogmodel_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthormodel',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='blogauthormodel',
            name='title',
        ),
    ]
