# Generated by Django 5.1.5 on 2025-01-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blogauthormodel_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blogs.blogtagmodel', verbose_name='tags'),
        ),
    ]
