# Generated by Django 5.1.5 on 2025-01-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blogauthormodel_first_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthormodel',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='blogauthormodel',
            name='first_name_uz',
        ),
        migrations.RemoveField(
            model_name='blogauthormodel',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='blogauthormodel',
            name='last_name_uz',
        ),
        migrations.RemoveField(
            model_name='blogcategorymodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogcategorymodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='blogtagmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogtagmodel',
            name='title_uz',
        ),
    ]
