# Generated by Django 5.1.5 on 2025-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blogauthormodel_first_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='first_name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='first_name_uz',
            field=models.CharField(max_length=125, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='last_name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='last_name_uz',
            field=models.CharField(max_length=125, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_en',
            field=models.CharField(max_length=125, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=125, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=125, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=125, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_en',
            field=models.CharField(max_length=125, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_uz',
            field=models.CharField(max_length=125, null=True, verbose_name='title'),
        ),
    ]
