# Generated by Django 5.1.5 on 2025-01-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_colormodel_heh_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='heh_code',
        ),
        migrations.AddField(
            model_name='colormodel',
            name='code',
            field=models.CharField(default=2024, max_length=125, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title',
            field=models.CharField(default='sasa', max_length=125, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='dsadsaas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.colormodel', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=125, verbose_name='title'),
        ),
    ]
