# Generated by Django 5.1.5 on 2025-01-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_image_productmodel_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=125, verbose_name='name'),
        ),
    ]
