# Generated by Django 5.1.5 on 2025-01-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productmodel_description_alter_tagmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=125, verbose_name='name')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='shop.productcategorymodel', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(default=1234, max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='shop.tagmodel', verbose_name='tags'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes', to='shop.productsizemodel', verbose_name='size'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(related_name='colors', to='shop.colormodel', verbose_name='color'),
        ),
    ]
