# Generated by Django 5.1.5 on 2025-01-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productmodel_in_stuck_productcommentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorModel',
            new_name='ProductColorModel',
        ),
        migrations.RenameModel(
            old_name='TagModel',
            new_name='ProductTagModel',
        ),
    ]
