# Generated by Django 5.1.5 on 2025-02-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_colormodel_productcolormodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=2024, max_digits=10),
            preserve_default=False,
        ),
    ]
