# Generated by Django 5.1.5 on 2025-02-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productmodel_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='discount_price',
        ),
    ]
