# Generated by Django 5.1.5 on 2025-02-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_productmodel_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
