# Generated by Django 5.1.5 on 2025-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productmodel_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
